"""empty message

Revision ID: a0537f065335
Revises: 28f254ccc0af
Create Date: 2020-04-28 23:21:09.709941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0537f065335'
down_revision = '28f254ccc0af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=False))
    op.drop_constraint('todos_lilst_id_fkey', 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'todolists', ['list_id'], ['id'])
    op.drop_column('todos', 'lilst_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('lilst_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key('todos_lilst_id_fkey', 'todos', 'todolists', ['lilst_id'], ['id'])
    op.drop_column('todos', 'list_id')
    # ### end Alembic commands ###
